tap "homebrew/bundle"
tap "FelixKratz/formulae" # for sketchybar, borders
tap "nikitabobko/tap"

brew "actionlint"
brew "aqua"
brew "atuin"
brew "bat"
brew "borders"
brew "curl"
brew "codex"
brew "colima"
brew "difftastic"
brew "direnv"
brew "docker"
# need to create a symlink for ~/.docker/cli-plugins/docker-buildx
# to /opt/homebrew/Cellar/docker-buildx/<version>/bin/docker-buildx
# or use `docker buildx install` after installing docker-buildx
# see
brew "docker-buildx"
brew "docker-credential-helper"
brew "docker-compose"
brew "duckdb"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "glow"
brew "gnu-sed"
brew "go"
brew "gojq"
brew "hugo"
brew "jnv"
brew "jq"
brew "kubectx"
brew "libpq"
brew "marp-cli"
brew "mcap"
brew "mise"
brew "mpdecimal" # required by google-cloud-sdk
brew "go-parquet-tools"
brew "podman"
brew "protobuf"
brew "ripgrep"
brew "shellcheck"
brew "sheldon"
brew "sketchybar"
brew "tenv"
brew "terraform-docs"
brew "tree"
brew "wget"
brew "xh"
brew "zola"
brew "zoxide"
brew "zsh"

cask "1password"
cask "antigravity"
cask "appcleaner"
cask "eul"
cask "karabiner-elements"
cask "font-hack-nerd-font"
cask "gcloud-cli"
cask "imageoptim"
cask "nikitabobko/tap/aerospace"
cask "notion"
cask "qlmarkdown"
cask "raycast"
cask "slack"
cask "visual-studio-code"
cask "wezterm@nightly"
cask "zoom"

if File.exist?("#{ENV['HOME']}/.Brewfile.local")
  instance_eval(File.read("#{ENV['HOME']}/.Brewfile.local"))
end
