tap "homebrew/bundle"
tap "aquaproj/aqua"
brew "actionlint"
brew "aquaproj/aqua/aqua"
brew "atuin"
brew "bat"
brew "curl"
brew "difftastic"
brew "duckdb"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "gnu-sed"
brew "go"
brew "gojq"
brew "hugo"
brew "jnv"
brew "jq"
brew "kubectx"
brew "libpq"
brew "marp-cli"
brew "mise"
brew "mpdecimal" # required by google-cloud-sdk
brew "podman"
brew "readline" # required by google-cloud-sdk
brew "ripgrep"
brew "shellcheck"
brew "sheldon"
brew "sqlite" # required by google-cloud-sdk
brew "tenv"
brew "terraform-docs"
brew "wget"
brew "xh"
brew "zola"
brew "zoxide"
brew "zsh"
cask "appcleaner"
# cask "cursor"
cask "eul"
cask "ghostty"
cask "google-cloud-sdk"
cask "imageoptim"
cask "podman-desktop"
cask "wezterm"

if File.exist?(".Brewfile.local")
  instance_eval(File.read(".Brewfile.local"))
end
