[tools]
node = "23.11.1"
npm = "11.11.1"
"npm:@openai/codex" = "latest"
"npm:@sakasegawa/ncli" = "latest"
"npm:corepack" = "0.34.7"
"npm:difit" = "latest"
"npm:nano-banana-mcp" = "latest"
"npm:pnpm" = "10.9.0"
python = "3.13"
rust = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
